### ISSUE TITLE
add build number to npm package version

### ISSUE THREAD

**Issue by balmas** [alpheios-project/node-build#27]
NPM won't let you publish two packages with the same name and version

we want to publish every dev, qa and prod build of components and embed-lib to npm

if we don't increase the package.json version until the prod build, we are going to have problems publishing intermediate builds of qa and dev to npm

perhaps we can solve this by running `npm version` and inserting the build number into the package.json before running the `npm publish` command in the build environment.

Ideally this solution will make sure that each incremental build of qa and dev is higher semantically than the prior.

The minimum requirement re semantic version comparisons is that each package pushed to the @latest tag is higher than the previous.

**Comment by kirlat** [comment]
Running `npm version`, or `lerna version` in Travis will change the files, and we have to commit them in order to be able to publish. We will also need to tag them, with some new (in order to be unique) tag to make a GitHub release. That's going to be pretty complex.

I think we can probable update the version (by adding a `branch-name.YYYYMMDDCCC` postfix to the version number) during a run of a tagged-commit script. Then those version changes will be committed along with other changes made during the script run. I think that would make sense because tagged commits are what we want to distribute eventually, and they should have "distributable" (i.e. npm publishable) version numbers.

What do you think?

**Comment by balmas** [comment]
that looked good to me.
